framework_web_01/Controllers/GioHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using framework_web_01.Models;

namespace framework_web_01.Controllers
{
    public class GioHangController : Controller
    {
        // GET: GioHang
        dbforwebprojectEntities DB = new dbforwebprojectEntities();
        // GET: GioHang
        const string cartname = "giohang";
        public ActionResult Index()
        {
            var giohang = (List<GioHang>)Session[cartname];

            //taikhoan khachhang = DB.taikhoans.Where(s => s.tendangnhap == (string)Session["tendangnhap"]).ToList().FirstOrDefault();
            return View(giohang);
        }


        public ActionResult ThemGioHang(int id)
        {
            if (Session["role"] == null)
            {
                Response.Redirect("https://localhost:44321/TaiKhoan/DangNhap");
            }
            var giohang = (List<GioHang>)Session[cartname];
            var sanpham = DB.sanphams.Find(id);
            if (giohang != null)
            {
                if (giohang.Exists(x => x.sanpham.masp == id))
                {
                    var sp = giohang.Where(s => s.sanpham.masp == id).FirstOrDefault();
                    sp.SoLuong += sp.SoLuong;
                }
                else
                {
                    GioHang gh = new GioHang(sanpham, 1);
                    giohang.Add(gh);
                }
                Session[cartname] = giohang;
            }
            else
            {
                GioHang gh = new GioHang(sanpham, 1);
                var list = new List<GioHang>();
                list.Add(gh);
                Session[cartname] = list;
            }
            return Redirect(Request.UrlReferrer.ToString());
        }
        [HttpPost]
        public ActionResult TinhLai(int[] id, int[] soluong)
        {
            var k = 0;
            var giohang = (List<GioHang>)Session[cartname];
            foreach (int i in id)
            {
                if (giohang.Exists(s => s.sanpham.masp == i))
                {
                    var sp = giohang.Where(s => s.sanpham.masp == i).FirstOrDefault();
                    sp.SoLuong = soluong[k];
                }
                k++;
            }
            return RedirectToAction("Index");
        }
        public ActionResult Diachi()
        {

            ViewBag.Title = "Diachi";
            string tendn = (string)Session["tendangnhap"];
            var sp = (from p in DB.taikhoans where p.tendangnhap == tendn select p).ToList();
            return View(sp);
        }
        [HttpPost]
        public ActionResult Diachi(FormCollection collection, hoadon hd)
        {
            hd = new hoadon();
            string stendangnhap = (string)Session["tendangnhap"];
            double stongtien = Convert.ToDouble(Session["tongtien"]);
            string ssdt = collection["sodt"];
            string sdiachi = collection["diachi"];
            string shoten = collection["name"];
            //gan du lieu vao model
            hd.tendangnhap = stendangnhap;
            hd.tien = stongtien;
            hd.sdt = ssdt;
            hd.diachi = sdiachi;
            hd.hoten = shoten;
            Session["dathang"] = hd;
            return RedirectToAction("DatHang");
        }
        [HttpGet]
        public ActionResult DatHang()
        {
            ViewBag.gh = (List<GioHang>)Session[cartname];
            ViewBag.dh = (hoadon)Session["dathang"];
            return View();
        }
        [HttpPost]
        public ActionResult DatHang(FormCollection collection)
        {
            List<GioHang> gh = (List<GioHang>)Session[cartname];
            hoadon dh = (hoadon)Session["dathang"];
            DB.hoadons.Add(dh);
            DB.SaveChanges();

            int mahdMax = DB.hoadons.Max(u => u.mahd);

            foreach (var item in gh)
            {
                cthd chitiet = new cthd();
                chitiet.tensp = item.sanpham.tensp;
                chitiet.mahd = mahdMax;
                chitiet.masp = item.sanpham.masp;
                chitiet.soluong = Convert.ToInt32(item.SoLuong);
                chitiet.thanhtien = Convert.ToInt32(item.SoLuong) * Convert.ToInt32(item.sanpham.gia);
                DB.cthds.Add(chitiet);
                DB.SaveChanges();

            }

            Session.Remove("giohang");
            return RedirectToAction("ThongBao");
        }
        public ActionResult ThongBao()
        {
            return View();
        }



    }
}

framework_web_01/Controllers/HoaDonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using framework_web_01.Models;

namespace framework_web_01.Controllers
{

    public class HoaDonController : Controller
    {
        dbforwebprojectEntities DB = new dbforwebprojectEntities();
        // GET: HoaDon
        public ActionResult Index()
        {
            if (Session["tendangnhap"] != null)
            {
                ViewBag.Title = "Index";
                if (Convert.ToInt32(Session["role"]) == 1)
                {
                    var hd = (from p in DB.hoadons select p).ToList();
                    return View(hd);
                }
                else
                {
                    string tendangnhap=Convert.ToString(Session["tendangnhap"]);
                    var hd = (from p in DB.hoadons where p.tendangnhap==tendangnhap  select p).ToList();
                    return View(hd);
                }
            }
            else
            {
                return View();
            }
            
        }

        public ActionResult chitiethoadon(int mahd)
        {
            var chitiet = DB.cthds.Where(s => s.mahd == mahd).ToList().FirstOrDefault();
            var splq = DB.cthds.Where(s => s.mahd == chitiet.mahd).ToList();
            ViewBag.sqlq = splq;
            //Session["masp"] = id;
            return View(chitiet);
        }

    }
}

framework_web_01/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using framework_web_01.Models;
using System.Data.Entity;

namespace framework_web_01.Controllers
{
    public class SanPhamController : Controller
    {
        // GET: SanPham
        dbforwebprojectEntities DB = new dbforwebprojectEntities();
        // GET: SanPham
        #region[Create]
        public ActionResult ThemSP()
        {

            if (Convert.ToInt32(Session["role"]) == 1)
            {
                ViewBag.Title = "ThemSP";
                return View();
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult ThemSP(FormCollection collection, sanpham sp)
        {
            int iloai = int.Parse(collection["loaisp"]);
            string stensp = collection["tensp"];
            double dgia = double.Parse(collection["gia"]);
            string shinhanh = collection["hinhanh"];
            string smota = collection["mota"];

            //gan du lieu vao model
            sp.loai = iloai;
            sp.tensp = stensp;
            sp.gia = dgia;
            sp.hinhanh = shinhanh;
            sp.mota = smota;

            DB.sanphams.Add(sp);
            int c = DB.SaveChanges();
            return RedirectToAction("Index","Home");

        }
        #endregion



        //xem chi tiết sản phầm + xóa
        public ActionResult Chitietsanpham(int id)
        {
            var kt = DB.sanphams.Where(s => s.masp == id).Count();//kiem tra taikhoan co ton tai trong database hay k
            if (Convert.ToInt32(kt) > 0)
            {
                var chitiet = DB.sanphams.Where(s => s.masp == id).ToList().FirstOrDefault();
                var splq = DB.sanphams.Where(s => s.masp == chitiet.masp).ToList().Take(1);
                ViewBag.sqlq = splq;
                Session["masp"] = id;
                return View(chitiet);
            }
            else
            {
                return View();
            }
        }
        [HttpPost]
        public ActionResult Chitietsanpham(FormCollection collection) //xoa
        {
            int idsp = int.Parse(collection["masp"]);
            var x = DB.sanphams.Where(s => s.masp == idsp).FirstOrDefault();
            DB.sanphams.Remove(x);
            DB.SaveChanges();
            return RedirectToAction("Index","Home");
        }



        [HttpGet]
        public ActionResult SuaSP()
        {
            if (Convert.ToInt32(Session["role"]) == 1)
            {
                int id = Convert.ToInt32(Session["masp"]);
                var chitiet = DB.sanphams.Where(s => s.masp == id).ToList().FirstOrDefault();
                var splq = DB.sanphams.Where(s => s.masp == chitiet.masp).ToList().Take(1);
                ViewBag.sqlq = splq;
                return View(chitiet);
            }
            return RedirectToAction("Index", "Home");
        }
        [HttpPost]
        public ActionResult SuaSP( sanpham Sanpham)
        {
            try
            {
                DB.Entry(Sanpham).State = EntityState.Modified;
                DB.SaveChanges();
                return RedirectToAction("Index", "Home");
            }catch{
                return View();
            }
            
        }



        //timkiem
        public ActionResult TimKiem()
        {
            string tim=Request.Form["search_name"];
            Session["timkiem"] = tim;
            //string tim = Convert.ToString(Content("${search_name}"));
            ViewBag.Title = "TimKiem";
            //string tim = Convert.ToString(Session["tim"]);
            //string tim = "nam";
            var sp = (from p in DB.sanphams where p.tensp.Contains(tim) select p).ToList();
            return View(sp);
        }
    }
}

framework_web_01/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>@ViewBag.Title - Jolie Clothing</title>
    <link href="~/Content/fontawesome-free-5.14.0/css/all.min.css" rel="stylesheet" />
    <link href="~/Content/LayoutCSS.css" rel="stylesheet" />

   
</head>

<body>
    <div id="content">
        <div id="menu_top">
            <!--mo menutop-->
            <div id="logo">
                <a href="https://localhost:44321/"><img src="~/Content/images/logohome1.PNG" alt="LogoJolie" /></a>
            </div>
            <div id="top_left">
                <form method="POST" runat="server" action="https://localhost:44321/SanPham/TimKiem">
                    <div id="find">
                        <input type="text" id="search_name" name="search_name"  placeholder="nhập sản phẩm cần tìm"  />
                        <a id="btnFind" name="timkiem">Tìm kiếm</a>
                    </div>
                </form>
                <div id="qoute">
                    <h2>Yêu bản thân, may mắn tự nhiên tới</h2>
                </div>
            </div>
            <div id="top_right">
                <div id="right_top">
                    <div id="right">
                        <ul>
                            <li>@Html.ActionLink("Đăng ký", "DangKy", "TaiKhoan")</li>
                            @if (Session["role"] != null)
                            {
                                <li>@Html.ActionLink("Đăng xuất", "DangXuat", "TaiKhoan")</li>

                            }
                            else
                            {
                                <li>@Html.ActionLink("Đăng nhập", "DangNhap", "TaiKhoan")</li>
                            }

                        </ul>
                    </div>

                    <div id="left">
                        <h3><a href="@Url.Action("Index","GioHang")">Giỏ hàng</a></h3>

                        @*</a></h3>
                            <h3><a href="#">Giỏ hàng</a></h3>*@
                    </div>
                </div>
                <div id="right_bottom"><h2><a href="#">Contact us</a></h2></div>
            </div>
            <div id="danhmuc">
                <nav class="nav-main">
                    <ul>
                        <li>@Html.ActionLink("Túi", "Tui", "Home")</li>
                        <li>@Html.ActionLink("Giày, dép", "Giay", "Home")</li>
                        <li>@Html.ActionLink("Áo", "Ao", "Home")</li>
                        <li>@Html.ActionLink("Quần", "Quan", "Home")</li>
                        <li>@Html.ActionLink("Yếm", "Yem", "Home")</li>
                        <li>@Html.ActionLink("Chân váy", "ChanVay", "Home")</li>
                        <li>@Html.ActionLink("Váy", "Vay", "Home")</li>
                    </ul>
                </nav>
            </div>
            <div id="duongdan">
                <nav class="dd">
                    <ul>
                        <li><a>Chào @Session["tendangnhap"] (^-^)</a></li>
                    </ul>
                </nav>
            </div>
        </div> <!--dong menutop-->
        <div id="main">
            <!--mo main--->

            <div id="menu_left">
                <div class="main_menu">
                    <h3>Danh mục sản phẩm</h3>
                    <ul>
                        <li>@Html.ActionLink("Túi", "Tui", "Home")</li>
                        <li>@Html.ActionLink("Giày, dép", "Giay", "Home")</li>
                        <li>@Html.ActionLink("Áo", "Ao", "Home")</li>
                        <li>@Html.ActionLink("Quần", "Quan", "Home")</li>
                        <li>@Html.ActionLink("Yếm", "Yem", "Home")</li>
                        <li>@Html.ActionLink("Chân váy", "ChanVay", "Home")</li>
                        <li>@Html.ActionLink("Váy", "Vay", "Home")</li>
                        
                        @if(Session["role"] != null)
                        {
                            <li>
                                <a>Quản lý</a>
                                <ul class="submenu">
                                    <li>@Html.ActionLink("Tài khoản cá nhân", "QuanLyTaiKhoan", "TaiKhoan")</li>
                                    @if ((int)Session["role"] == 0)
                                    {
                                        <li>@Html.ActionLink("Danh sách hóa đơn", "Index", "HoaDon")</li>
                                    }
                                    @if ((int)Session["role"] == 1)
                                    {
                                        <li>@Html.ActionLink("Thêm sản phẩm", "ThemSP", "SanPham")</li>
                                        <li>@Html.ActionLink("Danh sách tài khoản", "DanhSachTK", "TaiKhoan")</li>
                                        <li>@Html.ActionLink("Danh sách hóa đơn", "Index", "HoaDon")</li>
                                    }
                                </ul>
                                
                            </li>
                        }

                    </ul>
                </div>
            </div>

            <div id="hotdeals">
                <!--<?php
                require_once "./MVC/views/pages/".$data["Page"].".php";
                ?>-->
                @RenderBody()
            </div><!--dong sanpham-->
        </div><!--dong -main-->
        <footer>
            <div class="footer-wrap">
                <div class="footer-wrap-info">
                    <div class="footer__shopInfo-aboutus">
                        <h4 class="footer__shopInfo-aboutus-heading">Về chúng tôi</h4>
                        <ul class="footer__shopInfo-link-list">
                            <li class="footer__shopInfo-link-item">
                                <a href="#" class="footer__shopInfo-link">Shop chúng tôi</a>
                            </li>
                            <li class="footer__shopInfo-link-item">
                                <a href="#" class="footer__shopInfo-link">Báo cáo thường niên</a>
                            </li>
                            <li class="footer__shopInfo-link-item">
                                <a href="#" class="footer__shopInfo-link">Cơ hội việc làm</a>
                            </li>
                            <li class="footer__shopInfo-link-item">
                                <a href="#" class="footer__shopInfo-link">Chính sách cộng đồng</a>
                            </li>
                        </ul>
                    </div>

                    <div class="footer__contact-container">
                        <h4 class="footer__shopInfo-aboutus-heading">Liên lạc với chúng tôi</h4>
                        <p>Số điện thoại: <span>+84378233356</span></p>
                        <p>Hoặc</p>
                        <div class="footer__contact-icon-container">
                            <div class="footer__contact-icon">
                                <a href="#" class="footer__contact-icon-link">
                                    <i class="fab fa-facebook"></i>
                                </a>
                            </div>
                            <div class="footer__contact-icon">
                                <a href="#" class="footer__contact-icon-link">
                                    <i class="fab fa-instagram"></i>
                                </a>
                            </div>
                            <div class="footer__contact-icon">
                                <a href="#" class="footer__contact-icon-link">
                                    <i class="fab fa-twitter"></i>
                                </a>
                            </div>
                            <div class="footer__contact-icon">
                                <a href="#" class="footer__contact-icon-link">
                                    <i class="fab fa-youtube"></i>
                                </a>
                            </div>
                        </div>
                    </div>

                    <div class="footer__address-container">
                        <h4 class="footer__shopInfo-aboutus-heading">Địa chỉ của chúng tôi</h4>
                        <p>
                            Quận 1, Thành phố Hồ Chí Minh
                        </p>
                    </div>
                </div>

                <div class="footer-wrap-copyright">
                    <p>
                        Bản quyền © thuộc về Jolie Clothing Shop
                    </p>

                    <div class="footer-wrap-copyright-link-container">
                        <a href="#" class="footer-wrap-copyright-link">Contact</a>
                        <a href="" class="footer-wrap-copyright-link">Terms of Use</a>
                        <a href="" class="footer-wrap-copyright-link">Privacy</a>
                        <a href="" class="footer-wrap-copyright-link">Cookies</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>

</body>
</html>

framework_web_01/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title- Jolie Clothing</title>

    @*<link href="~/Content/DangNhapCSS.css" rel="stylesheet" />*@
    @if (@ViewBag.Title == "DangNhap")
    {
        <link href="~/Content/DangNhapCSS.css" rel="stylesheet" />
    }
    else
    {
        <link href="~/Content/DangKyCSS.css" rel="stylesheet" />
    }

    @if (@ViewBag.Title == "GioHang" || ViewBag.Title == "DatHang"|| ViewBag.Title == "DanhSachTK"|| ViewBag.Title=="Index" || ViewBag.Title == "chitiethoadon")
    {
        <link href="~/Content/GioHang.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    }

    <link href="~/Content/fontawesome-free-5.14.0/css/all.min.css" rel="stylesheet" />

    <!-------- nhúng icon ----------->
</head>
<body>
    <div class="container">
        <header>
            <div id="menu_top">
                <!--mo menutop-->
                <div id="logo">
                    <a href="https://localhost:44321/"><img src="~/Content/images/logohome1.PNG" alt="LogoJolie" /></a>
                </div>
                <div id="top_left">
                    <form method="POST" runat="server" action="https://localhost:44321/SanPham/TimKiem">
                        <div id="find">
                            <input type="text" id="search_name" name="search_name" placeholder="Nhập sản phẩm cần tìm" />
                            <a id="btnFind" name="timkiem">Tìm kiếm</a>
                        </div>
                    </form>
                    <div id="qoute">
                        <h2>Yêu bản thân, may mắn tự nhiên tới</h2>
                    </div>
                </div>
                <div id="top_right">
                    <div id="right_top">
                        <div id="right">
                            <ul>
                                <li>@Html.ActionLink("Đăng ký", "DangKy", "TaiKhoan")</li>
                                @if (Session["role"] != null)
                                {
                                    <li>@Html.ActionLink("Đăng xuất", "DangXuat", "TaiKhoan")</li>

                                }
                                else
                                {
                                    <li>@Html.ActionLink("Đăng nhập", "DangNhap", "TaiKhoan")</li>
                                }

                            </ul>
                        </div>
                        <div id="left">
                             <h3><a href="@Url.Action("Index","GioHang")">Giỏ hàng</a></h3>
                        </div>
                    </div>
                    <div id="right_bottom"><h2><a href="#">Contact us</a></h2></div>
                </div>
            </div> <!--dong menutop-->
        </header>

        <main>
            @RenderBody()
        </main>

        <footer>
            <div class="footer-wrap">
                <div class="footer-wrap-info">
                    <div class="footer__shopInfo-aboutus">
                        <h4 class="footer__shopInfo-aboutus-heading">Về chúng tôi</h4>
                        <ul class="footer__shopInfo-link-list">
                            <li class="footer__shopInfo-link-item">
                                <a href="#" class="footer__shopInfo-link">Shop chúng tôi</a>
                            </li>
                            <li class="footer__shopInfo-link-item">
                                <a href="#" class="footer__shopInfo-link">Báo cáo thường niên</a>
                            </li>
                            <li class="footer__shopInfo-link-item">
                                <a href="#" class="footer__shopInfo-link">Cơ hội việc làm</a>
                            </li>
                            <li class="footer__shopInfo-link-item">
                                <a href="#" class="footer__shopInfo-link">Chính sách cộng đồng</a>
                            </li>
                        </ul>
                    </div>

                    <div class="footer__contact-container">
                        <h4 class="footer__shopInfo-aboutus-heading">Liên lạc với chúng tôi</h4>
                        <p>Số điện thoại: <span>+84378233356</span></p>
                        <p>Hoặc</p>
                        <div class="footer__contact-icon-container">
                            <div class="footer__contact-icon">
                                <a href="#" class="footer__contact-icon-link">
                                    <i class="fab fa-facebook"></i>
                                </a>
                            </div>
                            <div class="footer__contact-icon">
                                <a href="#" class="footer__contact-icon-link">
                                    <i class="fab fa-instagram"></i>
                                </a>
                            </div>
                            <div class="footer__contact-icon">
                                <a href="#" class="footer__contact-icon-link">
                                    <i class="fab fa-twitter"></i>
                                </a>
                            </div>
                            <div class="footer__contact-icon">
                                <a href="#" class="footer__contact-icon-link">
                                    <i class="fab fa-youtube"></i>
                                </a>
                            </div>
                        </div>
                    </div>

                    <div class="footer__address-container">
                        <h4 class="footer__shopInfo-aboutus-heading">Địa chỉ của chúng tôi</h4>
                        <p>
                            Quận 1, Thành phố Hồ Chí Minh
                        </p>
                    </div>
                </div>

                <div class="footer-wrap-copyright">
                    <p>
                        Bản quyền © thuộc về Jolie Clothing Shop
                    </p>

                    <div class="footer-wrap-copyright-link-container">
                        <a href="#" class="footer-wrap-copyright-link">Contact</a>
                        <a href="" class="footer-wrap-copyright-link">Terms of Use</a>
                        <a href="" class="footer-wrap-copyright-link">Privacy</a>
                        <a href="" class="footer-wrap-copyright-link">Cookies</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <script>
        var icon_hide = document.querySelector(".icon-hide");
        var icon_show = document.querySelector(".icon-show");
        var password = document.querySelector('input[name="password"]');
        icon_hide.onclick = function (e) {
            e.target.style.display = "none";
            icon_show.style.display = "block";
            password.setAttribute('type', 'text');
        }

        icon_show.onclick = function (e) {
            e.target.style.display = "none";
            icon_hide.style.display = "block";
            password.setAttribute('type', 'password');
        }
    </script>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://unpkg.com/sweetalert@2.1.2/dist/sweetalert.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <script src="./public/js/main.js"></script>

</body>
</html>